services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: sfe_api
    restart: unless-stopped
    ports:
      - '2025:2025'
    env_file:
      - .env
    networks:
      - shared-network

networks:
  shared-network:
    external: true
