services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: sfe_api
    restart: unless-stopped
    ports:
      - '2025:2025'
    env_file:
      - .env
    volumes:
      - logs-volume:/app/logs
    networks:
      - shared-network

volumes:
  logs-volume:

networks:
  shared-network:
    external: true
