apiVersion: apps/v1
kind: Deployment
metadata:
  name: clean-arch-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clean-arch-api
  template:
    metadata:
      labels:
        app: clean-arch-api
    spec:
      containers:
        - name: clean-arch-api
          image: mydockerhubuser/clean-arch-api:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: clean-arch-service
spec:
  type: LoadBalancer
  selector:
    app: clean-arch-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
